apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAfF/os4a5mIgH6xxEXALuC1GoCk6ANwSvd6xHTZVlT9OHWnaLxruRcA8Ubke6nT+HONw9TwlmKuU2cPz8ih523REjxOshsOeMKr+ITsUY4HBEYAZ/wm44cukZt+9mnVveFpHWFfpdecnQTv/HeGzYXskIkpR1jPAOfqaCgw9omHY0+vPKeAWkWx+VoLy8LAezmFWYZaSsWCV92sxC2nW6G0cFwGCuXRL+DUd0ZquuaTvQSqWHCAkDuGzEdUQdbwYCETiBEImttnBHksKFMEGjDL5f3+5N/YZDxJU2NCJs2Oo6BK5ZFRxApQmQTfH10+38s/0ZrO3aE5MeJfCQCer7FPnC4DeHkJLi2mwVIZvReyV3eOz6vcIn4Ukug29MDiSJh2DXD2DQkaUcZVUt/QElHIXFpf1qJoDRX0QcZs2eQ1/eEePeUbF0Ub4zM42LwsZ9yWK0Pik1u9eivbiwK196WGDC1kkT/LDuP9aQPPiuGqdiLMjjJI5A6stniIQ72rGDWTwScqLM1sCfa0tco3CR1JJgVAHWvi71K2Cx6SMO7eWzrpO3dNnWN/F3w0KyzfqeReYi1IevltUqdhlxaibmyxzjxaYXrlFmQPL0ZF+MTreOdgKBfSPm6tM7roxKlX14so8MOAlZC1G5Z49zYF616P1/mZfFT6VZEuqYMfBHDip/+GnGIlEn10rBVHSxzFfLOg3UKY89grJA+KDbEcdqzXFvoymoQaBmt48zPaQc0faEoqlX1Fw==
    ARTIFACTORY_PASSWORD: AgCAUSZOvioz7gjERFkFQKLXhOtTnD3iX6UtJp0QZ3BKLcfgyu8BIFyv0bsLhQ//Nrm6T5eZyWwaHDOcuksHQpxZ/JsLzK2GLKB/cNzh9bSzukI0ROK9byP065B37+Lm6O6MrPKvko2uY49CGB5AposG3VjjkChaJAiXsvNY1LTvQ7HKTT03IR7BI/5MUx8C2i8mFe808d/1pes0TgAGAMrSxV77AywkE04gNM4LmKjhezfCFAbO++3tUQPZ6Lmq4U7m9/gDlzEBAn39lJiOR4dRC1Ir6Xq5Skguc2+KWJy+PaBztHt8p067gYu8Mq5K/cHUUtDL93KzMO4/Ka6scDDsyH0aYA135PJDP89V3mdqrQFyEWkHIhSwmghoZBS8bXp6LLbAGhq7sxfQA+NVggR8Wg5Rn48qlSlSNBpkBUSa5m1tsuA9xKxARRNlMNFfLtDPxRbKxOjJtIAu+7rMQGzd1FIkjH1tNGBK1qN3OTlQ8HzCrWsMJJmuX6Ri+DWSwvICshOMUcUsnZYOH2Vg/QqKB20FnI3VeoJ5r6S3GLw/wj06M/IlZmdFkSP9IRquWRuyQMSyeWV3I3sFlT8rVIqCjHryOoHApqZQtme+RjtL4WFCoaYlQx+yhqoq29IN888cijgbxgiwIZJVt+9Lg11kZ6guKPwbzGZxIYibknmeUoiOkimteZ74Jak9Gok7UIb7E5y2Sbe9jRsy5nO0zsrQitSLpw==
    ARTIFACTORY_URL: AgBXPwXnCvMwvQ2oIvSyCHz06/nQYtrX9XMmv8GHUN9J2mF6kdlgHMmcaJ0GwkkaOeKBEtK6mnwR8Tyx2mmMUZVhJFJlfNDWq9WPDCdjH0CxsCNQtVhjE79T9Qs/Yc4iAD+Zsa5Bo3o7OrHFq4AHgOUGKWTyVCWrm6xrM/axvRTkJ0tqf3fbEBMRFGX0Z9KU25ZuD9UsSvPkUPFzMv17vVzJ8AUKRWjm9DgCPROwUYfVwBqQB4Jf4QXCH8ZufHCzUGxtmRQEqfYc6hxdvhrmd+jeF3c8uI6V1aYALfBYOtWBtI50G8tJoJVaWvI5dWgrZkE85zQkKTsEeAox1mUdbQzsX5At2ztYcRo1xmYrc0utbbAT+BE0ejCJKc386zDSM4h19fYDi/0rQBJhcfAEUnDTTwyVDg/L0huZ3yjEdUXL/5UWshqhcM4yqvZ2q4FgXvxpKdGDo8g7BXx9Q6JLBS9ikduOcjSyRJrwulUuMJ5ITYZ1EzRKu3ToQK5EnxKRnc9GY9GHb0X2CkFd9b6hSsgJwQXIjpKNqIcNa6Ig1kivTsCN1rUdmddWN0fPs+jW4mjDVPRhsyW8wYaHK9ytNc0NoEGmhol4aUAymLJJlLr87nw/673Suv395IRCKhx1LgmpMPcphZF4wDcVwOegyJuJmRJLfqNek54BOs4C4sqv8SRxS3fV97hxZvxEEc0foHbOL3VTJ2DpNeMGF+RAA43p3fmuaiRQM+ONUKkN/7AkSNMEQY+ZAfDaNA==
    ARTIFACTORY_USER: AgAtpF9eETy3vHn++L6W0Tj79AO80wkgKV8epNiJPr92WmDpCw9NnrZtFRgb/WuaWPoooaUr2S7Cl+/UMwlhFc5l+6jGvpbXbXOLu2Bb67Mji5shPf4n0aCs5ceypD6UwavRlF8hfEyB+JfGqXxMD3mKbqulJY0YDIYXl9oaCSJ6gXgu9HOWGB1nPU+Z7xwid45y5jefA4lPwVVjgL5ToC49praPa3/XrMcvCRVH0QLC4FRsfTA5WrAOMXd48hnHzO8DRVcbNOTYfNP0y7mZLMnPZGCoXxKsaciSgs5fmiZra+g024K4vXyd/KZvLeO0vfEtuC0gKRqrViQm97a3ZG6Zwf2Kjp/LwWbRkSQXDdpk31u60xsXbAtGgbZ9ACBFwdq/72ieKgi+JMX2iWM5l7oqSl+LCdGBYNsDuOG5+wCzg/0tLp5AKtMwmbKM1p1lhBnnAWj8TJMwKapW8/7mk7vu3uZpaFow1eeh7vgLOP7dM1HH4Jjrr9z80d0xYyxVO2eR3mJzb9AUBOMv9lsKaNU7Sa022y1wSumN556N6mXzx6zT1h1f5KoQNsxKRlrhdmZCIfpleesVW8Z7m1RAdVw2AlREyor0Rbe9jeuMQJ2PPXIrNkKu/TstK/GiZZRIgx/nub9HOMmk2pRfVQOxmvkhyhQZ2P1a+WQYa2XIE3caIGoihZ1oGc3Fo9A+tlK1pMWsemS8fQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2022-01-14T19:59:39Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2022-01-14T20:01:23Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

