apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgBgQDjnya5ZvccO470ju/TUU8YY15AjdJJoBpog6uZE2zmTjawOS+KFwb+G7RMZ87yyU+v8ab8VvHvSOSECbPYAyBVfmT0gkSrNUgfUiJjqOSN+z7ENmkxGQmU2gR7eCBaoUzKES5/OoEV8D3DGceb8MP6SEXHFaENJtyzHss3RPy+tzlolLVmI6f4TX4r1qnSA8rBwY+U9jNKgR9PkqjeaGKe30dAZd9FWgha7H+ZJ9jGComN6mUjULn28lCEyZ+gSXQwOPM1WWRu00zCKyemk8eazJF3PdZzT/5DZ1GawyL3fkVEV35QKvoxkNDitUmeCDZY13LwKYUcWrWuF3dcZIVq0tUeWUT285nejuIQ3ro0bBYOQKYJYBb47bCztWFWmrjrfrQqsQE/TY3KB3p266nKwUq2bquH4XXkvkOTnQyz3xjk3IBKZ5m9dgxX3xioCtJ/ObxDNQNTncDpUPvGJodho357kt1B+tO6rYcSNKLpokrMRLso72bv4EEIfKbhErdNcpNV5FEzspFZcLdK/+ONq1xijY9hqS4DqnkE4hRNuoEIU90yMwk+fYXfdo7H620x8+H1jpEV2tbwppgw/cuCCDWO6WL1RtlOvlF847LNbYLMGwMMZfGxRocglZqfRrgOzPbIcfVonwVEWmlDPcL77go/trKVz1k9B1EtWT1gTzTx8Zcf0uJYZo2OjrAQdX69KrBr5T7S9tapQnYeYwdNp8KllByflXi0qhDjLi6IiCTaJvssd
    username: AgBmrvh6ENtSFin093QtRwI1Xc+I1AwUykPGIhWDbxgcw7Rkhxstiaqd4SE8dPxyhQjc5BepL+lSLDJkSzyAe+imbcEcBEvG0TvDU6o2RBxYbNuRKS4PMxKnpGJHZkVexy0At7CqfHR7frs0cjxA69cud8J/K3WMN/gkxG6cwsP3C1aXsRt9qCa5YLJIKgKR+Y/AX2Ju+2ENBc4xxb6J7Wab6VdPXZqlq+2zEzCB80jb48ELQb8cBzrdQyz42IwBaGn5gZnnN1u7ByGbOfs1/0PMvj755gw2U3s1uHLWUnaq9jIRU8jBtlzfq+YCoTl46QgSNp+a8nXwcl1pEkvdMN6U1ZwpaeGIEwxnA5CMiOucvoUnUjuYgZd16mZWGYJ7HEpDS2GxeHFwB0jyTeJvvgkzv7iA+7k6kNQKlI/yk9k7GRnWP/euGoGnVYTB/TnPUtUum6eCzqoKLBsmiBKyB8Hi+oLl9/MVp+TBvKHOZfPICIEtvwNjqHsvFWlAM7rUc0ZZq2PtAH7KqHj//FLzh4ORmGsfXzWYmdBe2JE3QHg+moop+38DIXdHlzESd8xWMrA2IDNEpaGMhPP2M6jBPrk02K1jyi64Y57SmOzeSl8p2LJq9TomsRi9KM3n6yaaOD9nVspZSIeBhLNOBHXhoZOQ2GKRc3ktC4DH8M+5rbwGvV/0nOfw3lD7zl+M6QGIgoSztAljm5w70IM=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

