apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgB2cIB7TUZ0C3Xl7hD+F+24Xzc3MriqJXMfFBns6d7hDPxPPxtuzTDwkeecKlCEQ0/OwG9PFZe+BEUH031xyKrvsUT4bIqsOOU+a+QG7d1nHFjc0YdU8mU9b5Za4XJlj8q0olXZ/3FnJYl+SOgHZQ8JqHssk5w6Ca6M3jrw9kyH15IebaQ1GeA80Z8xD8NNXYeyncX8jf3ykkNp6kFR5nyWFduCxl568ARXTnVE8PtDefsKN/P2Kzt5WmjJQFaowK5A8GddWokt7Z3qoZQvv5uVhjJunwxQpwRoiSRZ/HCdkeUVSnew07e7W/4DJHAqB9U5B0j9tgBuW2pw+8GLRfd7Ur0QcWy0syZHGs+D4Z6KLVRvSSAJYYRAcWrf4lxAMjQqHauTI5DjO4mDqQ9eiMqpeNzGCDSiWJFtPSrJFdeYFnvazbzK8EDtCi40KPWdloaUCJPqqYAQ6w5fdjYWAPqm5g8ChHCAM4xnAF6Fyv7ZV0p5FiuyLF3CoOkVssz8SHkIyCzXEvBaHPHq4nlyW0SWaYEHAD+YStExbTtI2GGhXO+BLfAeFgVQr3okjJeHHzowaDdVDW9ONk88T+Hd2NMFqOWajZre7Lm0TMPsOAvtcNToc60nSBkS7HM4jGtyRcqThdzH0S1WNhTx3CL1RTz3k3o/NwyjBXsxZgMOAZSxLZqnVBwVk/dVHrQbNrlBBT+z1J3BNGItQ3bSZXJt/KAGpAAQ1TkNvcuFKlc9n3nIQC6IYGxoXpSWZZtB6GHFcBK04VtQsqhK98lHiKWbbip6xwH3oZLnM530vIe6vIBSy5od8xlSJ4+EqOg1DC2CAX0duE8jQPx8qzjHqez7TtyL98MBc5T4rdaGHWOHrYKF2TT6r9jctSqFEQJh+nWQCK43s516OLDkGK1TEYKwBVqT16KuzYfW62Odi9lBjDZpEjeuKZAmNwhqfHVNhp1Ei0w=
    IBM_ENTITLED_REGISTRY_USER: AgAT39p5wghGaz+maNAH3bgYAd8awwMrPYUG9k+WfgLs7hegsrjpRyuQizUdMMbnyP5Mwyz/4ZDJZRtSGVuKfztyd37T37xSAIHPXDZK4X1ptq7SUD7RC8bMDZebY+Vdmm3VKZNnqJcOIvgNH0I17k9OPN5+IjlxhWvYfaj0jXT7ruKRKyITtUI2Hj7lueVFnUBc/CDsnILh2jXTxIfEhxxnp4zLX/NqTaIAMdv/qw8/KeZ/0N0v7A0ON6TSD/NiNIsKN9ktF/rM0wmEwG1fWU8f3MNVaI/qlEiXDZG1baA8BIhBVfRfDC3wEbo7w5R5eyIpSRizmzet/KiQ7TIPJ1PD9M8c0rJ6ULAEUrUr63fXVPukAAo7fHrhsY41oIWVkgBU55ekYXrZFI4SiwGWphmLQov/QtHPZgXXlDhFBCVE7aY8LBCb8i+ntIIZXoOy6dq2iYypxqb9sWeyp2114zKg/E3+cRhyAkyB/AAxSreejm9nZPtMCNvm6OzKSp+nTI6kTRUvq51txRnnLB2LyejmtYa2ptfHtGAdyEVME3wn5Jy5h4ASmikuxjnon6ax5g2q+GwP1rT45yyRP2Ux7sVLUN23DL4P5jHFQF80p0D+5DPAdORjEm87O6ixcN0rJ+WdhocFD/GS65rFg/Idc5dXJ/BkrPuxZkO3Jr6tcDYnX/EGEkiBJWGEZl8GbHEXEsLu1A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

